name: release-please
on:
  push:
    branches:
      - 2.x

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          # Use 'node' for JS/TS projects, or 'simple' for general repos
          release-type: simple 
          token: ${{ secrets.GITHUB_TOKEN }}
    
      # Automatically merge the Release PR if it was created
      - name: Auto-merge release PR
        if: ${{ steps.release.outputs.pr }}
        run: gh pr merge "${{ steps.release.outputs.pr }}" --auto --squash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
